apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netab-ingress
  namespace: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1

spec:
  rules:
  - http:
      paths:
      - path: /service-b
        pathType: Prefix
        backend:
          service:
            name: service-b
            port:
              number: 80
      - path: /service-a/(.+)
        pathType: Prefix
        backend:
          service:
            name: service-a-bitcoin
            port:
              number: 80
