apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  namespace: ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a-neta-bitcoin
        image: servicea.azurecr.io/service-a-neta-bitcoin:latest
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: ingress
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: service-a
