apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-bitcoin
  namespace: ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a-bitcoin
  template:
    metadata:
      labels:
        app: service-a-bitcoin
    spec:
      containers:
      - name: service-a-bitcoin
        image: servicea.azurecr.io/myapp/my-flask-app
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /readyz
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 60
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: service-a-bitcoin
  namespace: ingress
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: service-a-bitcoin
